#!/usr/bin/env python3
"""Certify a uniform dyadic L2 bound for the combined odd Loewner symbol.

For the V23 cutoff c=13, write F_n = S_n + P_n.  The workflow-produced
Archimedean certificate, generated by its tracked certifier, proves
abs(S_n-pi/4) <= D/n with D=1/4, while P_n is the finite prime-power sine
polynomial.  The endpoint q=c has phase 2*pi*n and vanishes exactly.

Expanding (pi/4+P_n)^2 leaves a constant mean plus finitely many geometric
sums.  Every prefix N<n<=N+r therefore has an affine square-sum upper bound.
Finite Abel summation and the reciprocal-square dyadic estimate then give

    N * sum_(N<n<=2N) F_n^2/n^2
      <= A(N)/2 + B*N/(N+1)^2.

All decaying coefficients are nonnegative, and N/(N+1)^2 decreases for
integer N>=1, so a strict check at one start mode controls every later mode.
Arb is used for every transcendental value and strict comparison.

The output is a rigorous constant-composition certificate.  Its proof-level
use remains conditional on the analytic Archimedean source identification and
the parity-shell operator bridge.  The companion Lean module now identifies
the literal finite prime entrywise builder with the normalized logarithmic
Loewner kernel, formalizes the finite geometric-sum inequality itself, the
exact logarithmic prime weights and phases, and symbolic nonresonance of every
single, doubled, pair-difference, and pair-sum phase in the tracked cutoff-13
event list, as well as the Abel, dyadic, endpoint-monotonicity, and
rectangular-Cauchy adapters.  This script independently interval-certifies the
positive denominator magnitudes needed for the numerical constants below.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import platform
import subprocess
from fractions import Fraction
from pathlib import Path
from typing import Any

import flint
from flint import arb, ctx

from certify_parity_gap import prime_powers_up_to


def _positive_fraction(text: str, name: str) -> Fraction:
    value = Fraction(text)
    if value <= 0:
        raise ValueError(f"{name} must be strictly positive")
    return value


def _fraction_arb(value: Fraction) -> arb:
    return arb(value.numerator) / arb(value.denominator)


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest().upper()


def _git_sha() -> str | None:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"],
            text=True,
            encoding="utf-8",
            stderr=subprocess.DEVNULL,
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return None


def _ball_record(value: arb, digits: int = 70) -> dict[str, str]:
    return {
        "midpoint": value.mid().str(digits, radius=False),
        "radius": value.rad().str(20, radius=False),
        "lower": value.lower().str(digits, radius=True),
        "upper": value.upper().str(digits, radius=True),
    }


def _load_json(path: Path, name: str) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"could not read {name}: {path}: {exc}") from exc
    if not isinstance(payload, dict):
        raise ValueError(f"{name} must contain a JSON object")
    return payload


def _require_true(payload: dict[str, Any], key: str, name: str) -> None:
    if payload.get(key) is not True:
        raise ValueError(f"{name} does not certify {key}=true")


def _validate_archimedean_certificate(
    *,
    path: Path,
    c: int,
    start_mode: int,
    centered_decay: Fraction,
    precision: int,
) -> tuple[dict[str, Any], dict[str, Any]]:
    payload = _load_json(path, "Archimedean certificate")
    if payload.get("status") != "PASS":
        raise ValueError("Archimedean certificate must have status PASS")
    _require_true(
        payload,
        "rigorous_constant_certificate",
        "Archimedean certificate",
    )
    if payload.get("c") != c:
        raise ValueError("Archimedean certificate cutoff does not match --c")

    minimum_mode = payload.get("minimum_mode")
    if not isinstance(minimum_mode, int) or minimum_mode > start_mode:
        raise ValueError(
            "Archimedean certificate does not cover the requested start mode"
        )
    certificate_precision = payload.get("precision_bits")
    if not isinstance(certificate_precision, int) or certificate_precision < precision:
        raise ValueError(
            "Archimedean certificate precision is below the requested precision"
        )

    centered = payload.get("centered_symbol_audit")
    if not isinstance(centered, dict):
        raise ValueError("Archimedean certificate lacks centered_symbol_audit")
    if centered.get("target_decay_coefficient") != str(centered_decay):
        raise ValueError("Archimedean centered-decay coefficient mismatch")
    _require_true(centered, "strict_upper_pass", "Archimedean centered audit")
    _require_true(centered, "strict_lower_pass", "Archimedean centered audit")

    script = Path(__file__).resolve().parent / ("certify_archimedean_tail_envelope.py")
    expected_script_hash = str(payload.get("script_sha256", "")).upper()
    actual_script_hash = _sha256(script)
    if expected_script_hash != actual_script_hash:
        raise ValueError(
            "Archimedean certificate script hash mismatch: "
            f"artifact={expected_script_hash}, current={actual_script_hash}"
        )

    current_git = _git_sha()
    certificate_git = payload.get("git_sha")
    if not isinstance(current_git, str) or len(current_git) != 40:
        raise ValueError("current checkout has no valid 40-character Git SHA")
    if not isinstance(certificate_git, str) or len(certificate_git) != 40:
        raise ValueError("Archimedean certificate has no valid 40-character Git SHA")
    if certificate_git != current_git:
        raise ValueError(
            "Archimedean certificate commit does not match the current checkout"
        )

    metadata = {
        "path": str(path.resolve()),
        "sha256": _sha256(path.resolve()),
        "script_path": str(script),
        "script_sha256": actual_script_hash,
        "git_sha": certificate_git,
        "minimum_mode": minimum_mode,
        "precision_bits": certificate_precision,
        "centered_decay_coefficient": str(centered_decay),
    }
    return payload, metadata


def _minimum_labelled(
    values: list[tuple[str, arb]],
) -> tuple[str, arb]:
    if not values:
        raise ValueError("phase denominator list is empty")
    label, value = values[0]
    for candidate_label, candidate in values[1:]:
        if candidate < value:
            label, value = candidate_label, candidate
    return label, value


def certify(
    *,
    c: int,
    start_mode: int,
    centered_decay: Fraction,
    target_scaled_upper: Fraction,
    precision: int,
    archimedean_certificate: Path,
) -> dict[str, Any]:
    if c <= 1:
        raise ValueError("c must exceed one")
    if start_mode < 1:
        raise ValueError("start_mode must be positive")
    if precision < 128:
        raise ValueError("precision must be at least 128 bits")

    _, arch_metadata = _validate_archimedean_certificate(
        path=archimedean_certificate,
        c=c,
        start_mode=start_mode,
        centered_decay=centered_decay,
        precision=precision,
    )

    ctx.prec = precision
    pi = arb.pi()
    length = arb(c).log()
    center = pi / 4
    decay = _fraction_arb(centered_decay)
    target = _fraction_arb(target_scaled_upper)

    all_prime_data = prime_powers_up_to(c)
    prime_data = [(q, p) for q, p in all_prime_data if q < c]
    endpoint_events = [(q, p) for q, p in all_prime_data if q == c]
    if not prime_data:
        raise ValueError("no nontrivial prime-power phases were found")

    weights = [arb(p).log() / arb(q).sqrt() for q, p in prime_data]
    phases = [2 * pi * arb(q).log() / length for q, _ in prime_data]

    labelled_denominators: list[tuple[str, arb]] = []
    half_sines: list[arb] = []
    double_half_sines: list[arb] = []
    for (q, _p), phase in zip(prime_data, phases):
        half = abs((phase / 2).sin())
        doubled = abs(phase.sin())
        half_sines.append(half)
        double_half_sines.append(doubled)
        labelled_denominators.append((f"single:{q}", half))
        labelled_denominators.append((f"diagonal:{q}", doubled))

    pair_denominators: list[tuple[arb, arb]] = []
    for i in range(len(phases)):
        for j in range(i + 1, len(phases)):
            difference = abs(((phases[i] - phases[j]) / 2).sin())
            total = abs(((phases[i] + phases[j]) / 2).sin())
            pair_denominators.append((difference, total))
            q_i = prime_data[i][0]
            q_j = prime_data[j][0]
            labelled_denominators.append((f"pair-difference:{q_i}:{q_j}", difference))
            labelled_denominators.append((f"pair-sum:{q_i}:{q_j}", total))

    if not all(value > 0 for _, value in labelled_denominators):
        raise RuntimeError("a geometric-sum phase denominator is not positive")
    minimum_label, minimum_denominator = _minimum_labelled(labelled_denominators)

    main = center**2 + sum((weight**2 for weight in weights), arb(0)) / 2
    symbol_abs = center + sum(weights, arb(0))

    linear_error = (
        2
        * center
        * sum(
            (weight / denominator for weight, denominator in zip(weights, half_sines)),
            arb(0),
        )
    )
    diagonal_error = sum(
        (
            weight**2 / (2 * denominator)
            for weight, denominator in zip(weights, double_half_sines)
        ),
        arb(0),
    )
    pair_error = arb(0)
    pair_index = 0
    for i in range(len(weights)):
        for j in range(i + 1, len(weights)):
            difference, total = pair_denominators[pair_index]
            pair_error += weights[i] * weights[j] * (1 / difference + 1 / total)
            pair_index += 1
    geometric_error = linear_error + diagonal_error + pair_error

    linear_decay_coefficient = 2 * decay * symbol_abs
    quadratic_decay_coefficient = decay**2

    n = arb(start_mode)
    prefix_slope = (
        main + linear_decay_coefficient / n + quadratic_decay_coefficient / n**2
    )
    scaled_weighted_upper = prefix_slope / 2 + geometric_error * n / (n + 1) ** 2
    if not scaled_weighted_upper < target:
        raise RuntimeError(
            "combined-symbol dyadic L2 target failed: "
            f"upper={scaled_weighted_upper}, target={target}"
        )

    monotone_coefficients = [
        linear_decay_coefficient,
        quadratic_decay_coefficient,
        geometric_error,
    ]
    if not all(value >= 0 for value in monotone_coefficients):
        raise RuntimeError("a decaying endpoint coefficient is negative")

    script_dir = Path(__file__).resolve().parent
    prime_power_source = script_dir / "certify_parity_gap.py"

    return {
        "status": "PASS",
        "rigorous_constant_certificate": True,
        "scope": (
            "Arb certification of the finite trigonometric constants and "
            "strict start-mode endpoint for the combined-symbol dyadic L2 bound"
        ),
        "c": c,
        "precision_bits": precision,
        "start_mode": start_mode,
        "target_scaled_upper": str(target_scaled_upper),
        "centered_decay_coefficient": str(centered_decay),
        "proved_for_every_integer_mode": f"N >= {start_mode}",
        "prime_powers_below_c": [list(item) for item in prime_data],
        "prime_power_count": len(prime_data),
        "zero_phase_endpoint_events_removed": [
            {"q": q, "p": p, "reason": "sin(2*pi*n)=0 for integer n"}
            for q, p in endpoint_events
        ],
        "combined_symbol": (
            "F_n=S_n+sum_(q<c) log(p)/sqrt(q)*sin(2*pi*n*log(q)/log(c))"
        ),
        "lean_concrete_source_formula": {
            "prime_symbol": (
                "RiemannCvs.CombinedSymbolDyadicL2.finiteLogarithmicPrimeSymbol"
            ),
            "combined_symbol": (
                "RiemannCvs.CombinedSymbolDyadicL2.logarithmicCombinedSymbol"
            ),
            "normalized_complete_kernel": (
                "RiemannCvs.CombinedSymbolDyadicL2."
                "oddDifferenceKernel_fourierNormalized_logarithmicCombined"
            ),
            "prime_diagonal": (
                "RiemannCvs.CombinedSymbolDyadicL2.finiteLogarithmicPrimeDiagonal"
            ),
            "prime_entry": (
                "RiemannCvs.CombinedSymbolDyadicL2.finiteLogarithmicPrimeEntry"
            ),
            "prime_event_entry": (
                "RiemannCvs.CombinedSymbolDyadicL2.logarithmicPrimeEventEntry"
            ),
            "prime_entrywise_sum": (
                "RiemannCvs.CombinedSymbolDyadicL2."
                "finiteLogarithmicPrimeEntry_eq_sum_eventEntries"
            ),
            "prime_entry_kernel_identification": (
                "RiemannCvs.CombinedSymbolDyadicL2."
                "finiteLogarithmicPrimeEntry_eq_oddDifferenceKernel"
            ),
            "combined_actual_diagonal_adapter": (
                "RiemannCvs.CombinedSymbolDyadicL2."
                "oddDifferenceKernel_logarithmicCombined_actualDiagonal"
            ),
            "normalized_loewner_source_entry": (
                "RiemannCvs.CombinedSymbolDyadicL2.normalizedLoewnerSourceEntry"
            ),
            "normalized_loewner_source_identification": (
                "RiemannCvs.CombinedSymbolDyadicL2."
                "normalizedLoewnerSourceEntry_eq_oddDifferenceKernel"
            ),
            "arch_prime_entry": (
                "RiemannCvs.CombinedSymbolDyadicL2.logarithmicArchPrimeEntry"
            ),
            "arch_prime_entry_identification": (
                "RiemannCvs.CombinedSymbolDyadicL2."
                "logarithmicArchPrimeEntry_eq_oddDifferenceKernel"
            ),
            "pole_kernel": ("RiemannCvs.CombinedSymbolDyadicL2.logarithmicPoleKernel"),
            "pole_displacement": (
                "RiemannCvs.CombinedSymbolDyadicL2.logarithmicPoleKernel_law"
            ),
            "cutoff_free_kernel": (
                "RiemannCvs.CombinedSymbolDyadicL2.logarithmicCutoffFreeKernel"
            ),
            "cutoff_free_kernel_identification": (
                "RiemannCvs.CombinedSymbolDyadicL2."
                "logarithmicCutoffFreeKernel_eq_pole_sub_oddDifferenceKernel"
            ),
            "cutoff_free_displacement": (
                "RiemannCvs.CombinedSymbolDyadicL2.logarithmicCutoffFreeKernel_law"
            ),
            "archimedean_frequency": (
                "RiemannCvs.CombinedSymbolDyadicL2.archimedeanFrequency"
            ),
            "archimedean_geometric_series": (
                "RiemannCvs.CombinedSymbolDyadicL2.archimedeanGeometricSeries"
            ),
            "archimedean_geometric_series_summable": (
                "RiemannCvs.CombinedSymbolDyadicL2."
                "summable_archimedeanGeometricSeries_terms"
            ),
            "archimedean_digamma_imaginary": (
                "RiemannCvs.CombinedSymbolDyadicL2.archimedeanDigammaImaginary"
            ),
            "archimedean_symbol": (
                "RiemannCvs.CombinedSymbolDyadicL2.logarithmicArchimedeanSymbol"
            ),
            "archimedean_symbol_odd": (
                "RiemannCvs.CombinedSymbolDyadicL2."
                "logarithmicArchimedeanSymbol_odd"
            ),
            "concrete_archimedean_cutoff_free_displacement": (
                "RiemannCvs.CombinedSymbolDyadicL2."
                "logarithmicCutoffFreeKernel_archimedean_law"
            ),
            "archimedean_argument": (
                "RiemannCvs.CombinedSymbolDyadicL2.archimedeanArgument"
            ),
            "archimedean_argument_reflection": (
                "RiemannCvs.CombinedSymbolDyadicL2.archimedeanArgument_neg"
            ),
            "archimedean_digamma_argument_identification": (
                "RiemannCvs.CombinedSymbolDyadicL2."
                "archimedeanDigammaImaginary_eq_argument"
            ),
            "archimedean_cosine_geometric_series": (
                "RiemannCvs.CombinedSymbolDyadicL2."
                "archimedeanCosineGeometricSeries"
            ),
            "archimedean_x_one_geometric_series": (
                "RiemannCvs.CombinedSymbolDyadicL2."
                "archimedeanXOneGeometricSeries"
            ),
            "archimedean_x_two_geometric_series": (
                "RiemannCvs.CombinedSymbolDyadicL2."
                "archimedeanXTwoGeometricSeries"
            ),
            "archimedean_diagonal_series_summable": [
                "RiemannCvs.CombinedSymbolDyadicL2."
                "summable_archimedeanCosineGeometricSeries_terms",
                "RiemannCvs.CombinedSymbolDyadicL2."
                "summable_archimedeanXOneGeometricSeries_terms",
                "RiemannCvs.CombinedSymbolDyadicL2."
                "summable_archimedeanXTwoGeometricSeries_terms",
            ],
            "archimedean_cosine_correction": (
                "RiemannCvs.CombinedSymbolDyadicL2.archimedeanCosineCorrection"
            ),
            "archimedean_cross_correction": (
                "RiemannCvs.CombinedSymbolDyadicL2.archimedeanCrossCorrection"
            ),
            "archimedean_kappa": (
                "RiemannCvs.CombinedSymbolDyadicL2.logarithmicArchimedeanKappa"
            ),
            "archimedean_pole_j": (
                "RiemannCvs.CombinedSymbolDyadicL2.logarithmicArchimedeanPoleJ"
            ),
            "archimedean_diagonal": (
                "RiemannCvs.CombinedSymbolDyadicL2.logarithmicArchimedeanDiagonal"
            ),
            "archimedean_diagonal_even": (
                "RiemannCvs.CombinedSymbolDyadicL2."
                "logarithmicArchimedeanDiagonal_neg"
            ),
            "actual_archimedean_cutoff_free_displacement": (
                "RiemannCvs.CombinedSymbolDyadicL2."
                "logarithmicCutoffFreeKernel_actualArchimedean_law"
            ),
            "cutoff_endpoint_zero": (
                "RiemannCvs.CombinedSymbolDyadicL2.logarithmicPrimeEndpoint_term_zero"
            ),
            "cutoff_endpoint_entry_zero": (
                "RiemannCvs.CombinedSymbolDyadicL2."
                "logarithmicPrimeEndpointEventEntry_nat_zero"
            ),
            "strict_interior_single_phase_nonresonance": (
                "RiemannCvs.CombinedSymbolDyadicL2.logarithmicPrimePhase_half_sin_pos"
            ),
            "cutoff_13_symbol": (
                "RiemannCvs.CombinedSymbolDyadicL2.c13FiniteLogarithmicPrimeSymbol"
            ),
            "cutoff_13_all_phase_nonresonance": (
                "RiemannCvs.CombinedSymbolDyadicL2.c13PrimePhase_all_nonresonant"
            ),
        },
        "geometric_sum_bound": {
            "statement": ("abs(sum_{n=a+1}^{b} exp(i*n*phi)) <= 1/abs(sin(phi/2))"),
            "lean_complex_interface": (
                "RiemannCvs.CombinedSymbolDyadicL2."
                "norm_shifted_exp_sum_le_inv_abs_sin_half"
            ),
            "lean_sine_interface": (
                "RiemannCvs.CombinedSymbolDyadicL2."
                "abs_shifted_sine_sum_le_inv_abs_sin_half"
            ),
            "lean_cosine_interface": (
                "RiemannCvs.CombinedSymbolDyadicL2."
                "abs_shifted_cosine_sum_le_inv_abs_sin_half"
            ),
            "concrete_nonresonance_interval_certified": True,
            "concrete_denominator_magnitudes_interval_certified": True,
            "lean_cutoff_13_all_phase_nonresonance": (
                "RiemannCvs.CombinedSymbolDyadicL2.c13PrimePhase_all_nonresonant"
            ),
        },
        "archimedean_input": (f"abs(S_n-pi/4) <= ({centered_decay})/n"),
        "affine_prefix_bound": (
            "sum_{n=N+1}^{N+r} F_n^2 <= "
            "r*(main+linearDecay/N+quadraticDecay/N^2)+geometricError"
        ),
        "abel_consequence": (
            "N*sum_{n=N+1}^{2*N} F_n^2/n^2 <= prefixSlope/2+geometricError*N/(N+1)^2"
        ),
        "monotonicity_certificate": {
            "all_decaying_coefficients_nonnegative": True,
            "reciprocal_terms": "1/N and 1/N^2 decrease for N>=1",
            "geometric_endpoint_identity": (
                "N/(N+1)^2-(N+1)/(N+2)^2=(N^2+N-1)/((N+1)^2*(N+2)^2)>0 for N>=1"
            ),
            "lean_adapter": (
                "RiemannCvs.CombinedSymbolDyadicL2."
                "dyadicEndpointScaledUpper_lt_one_of_start"
            ),
        },
        "constants": {
            "archimedean_center": _ball_record(center),
            "main_mean_square": _ball_record(main),
            "symbol_abs_triangle": _ball_record(symbol_abs),
            "linear_decay_coefficient": _ball_record(linear_decay_coefficient),
            "quadratic_decay_coefficient": _ball_record(quadratic_decay_coefficient),
            "linear_geometric_error": _ball_record(linear_error),
            "diagonal_geometric_error": _ball_record(diagonal_error),
            "pair_geometric_error": _ball_record(pair_error),
            "total_geometric_error": _ball_record(geometric_error),
            "minimum_phase_denominator": {
                "label": minimum_label,
                **_ball_record(minimum_denominator),
            },
            "endpoint_prefix_slope": _ball_record(prefix_slope),
            "endpoint_scaled_weighted_upper": _ball_record(scaled_weighted_upper),
            "endpoint_slack_below_target": _ball_record(target - scaled_weighted_upper),
        },
        "strict_target_pass": True,
        "lean_interfaces": {
            "affine_abel": (
                "RiemannCvs.CombinedSymbolDyadicL2."
                "dyadic_weighted_sum_lt_one_div_of_prefix_le_affine"
            ),
            "certified_endpoint": (
                "RiemannCvs.CombinedSymbolDyadicL2."
                "dyadic_weighted_sum_lt_one_div_of_endpoint"
            ),
            "all_scale_start_endpoint": (
                "RiemannCvs.CombinedSymbolDyadicL2."
                "dyadic_weighted_sum_lt_one_div_of_start_endpoint"
            ),
        },
        "conclusion": (
            "conditional on the Archimedean source and parity-shell identifications, for every "
            f"integer N>={start_mode}, "
            "sum F_n^2/n^2 over N<n<=2N is "
            f"< {target_scaled_upper}/N"
        ),
        "source_dependencies": {
            "archimedean_certificate": arch_metadata,
            "prime_power_enumerator": {
                "path": str(prime_power_source),
                "sha256": _sha256(prime_power_source),
            },
        },
        "python_version": platform.python_version(),
        "python_flint_version": flint.__version__,
        "platform": platform.platform(),
        "git_sha": _git_sha(),
        "created_at": dt.datetime.now(dt.timezone.utc).isoformat(),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--c", type=int, default=13)
    parser.add_argument("--start-mode", type=int, default=1920)
    parser.add_argument("--centered-decay", default="1/4")
    parser.add_argument("--target-scaled-upper", default="1")
    parser.add_argument("--prec", type=int, default=256)
    parser.add_argument(
        "--archimedean-certificate",
        type=Path,
        required=True,
    )
    parser.add_argument("--json-out", type=Path, required=True)
    args = parser.parse_args()

    result = certify(
        c=args.c,
        start_mode=args.start_mode,
        centered_decay=_positive_fraction(args.centered_decay, "centered_decay"),
        target_scaled_upper=_positive_fraction(
            args.target_scaled_upper, "target_scaled_upper"
        ),
        precision=args.prec,
        archimedean_certificate=args.archimedean_certificate.resolve(),
    )
    result["script_sha256"] = _sha256(Path(__file__).resolve())

    args.json_out.parent.mkdir(parents=True, exist_ok=True)
    args.json_out.write_text(
        json.dumps(result, indent=2) + "\n",
        encoding="utf-8",
    )
    print(
        json.dumps(
            {
                "status": result["status"],
                "precision_bits": result["precision_bits"],
                "start_mode": result["start_mode"],
                "strict_target_pass": result["strict_target_pass"],
                "endpoint_scaled_weighted_upper": result["constants"][
                    "endpoint_scaled_weighted_upper"
                ],
                "endpoint_slack_below_target": result["constants"][
                    "endpoint_slack_below_target"
                ],
                "artifact": str(args.json_out.resolve()),
                "sha256": _sha256(args.json_out.resolve()),
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
