from fractions import Fraction as F
from bisect import bisect_right
from pathlib import Path
import argparse
import hashlib
import json

C = F(13)
LAYER_THRESHOLDS = [F(6,5), F(3,2), F(5,3), F(15,8)]
EVENTS = [
    (2,F(491,1000)), (3,F(635,1000)), (4,F(347,1000)),
    (5,F(720,1000)), (7,F(736,1000)), (8,F(246,1000)),
    (9,F(367,1000)), (11,F(724,1000)),
]

def cuts():
    out = {F(1), C}
    for a in LAYER_THRESHOLDS:
        out.update((a, C / a))
    for qi, _ in EVENTS:
        q = F(qi)
        out.update((q, C / q))
        for a in LAYER_THRESHOLDS:
            out.update((a / q, C / (a * q), a * q, C * q / a))
    return sorted(x for x in out if F(1) <= x <= C)

CUTS = cuts()
assert len(CUTS) == 62

REGION_NAMES = ["low", "lowerOne", "lowerTwo", "lowerThree", "central",
                "upperThree", "upperTwo", "upperOne", "high"]
REGION_HEIGHT = [F(1),F(5,6),F(10,13),F(5,7),F(9,13),F(5,7),F(10,13),F(5,6),F(1)]
DIRECT_THRESHOLDS = [F(6,5),F(3,2),F(5,3),F(15,8),F(104,15),F(39,5),F(26,3),F(65,6)]
REGION_BOUNDS = [
    (None,F(6,5)), (F(6,5),F(3,2)), (F(3,2),F(5,3)),
    (F(5,3),F(15,8)), (F(15,8),F(104,15)),
    (F(104,15),F(39,5)), (F(39,5),F(26,3)),
    (F(26,3),F(65,6)), (F(65,6),None),
]

def region(x): return bisect_right(DIRECT_THRESHOLDS, x)
def height(x): return REGION_HEIGHT[region(x)]

def fmt(x, typed=False):
    x = F(x)
    raw = str(x.numerator) if x.denominator == 1 else f"{x.numerator} / {x.denominator}"
    return f"({raw} : ℝ)" if typed else raw

lines = []
a = lines.append
a("import RiemannCvs.PrimeTranslationSupersolution")
a("")
a("/- This file is generated by")
a("   `research/riemann-cvs-numerics/generate_prime_translation_continuous_supersolution.py`.")
a("   Edit the generator and replay its `--check` mode rather than hand-editing cells. -/")
a("")
a("/-!")
a("# Continuous cutoff-13 positive supersolution")
a("")
a("This generated module promotes the exact rational 61-cell certificate to")
a("every real multiplicative coordinate `t ∈ [1,13]`.  The generated cell")
a("lemmas use only ordered-field arithmetic; the true logarithmic weights are")
a("then transferred through the elementary strict bounds proved in")
a("`PrimeTranslationSupersolution`.")
a("-/")
a("")
a("noncomputable section")
a("")
a("namespace RiemannCvs.PrimeTranslationSupersolution")
a("")
a("def c13ContinuousSupersolutionHeight (t : ℝ) : ℝ :=")
a("  if t < 6 / 5 then 1")
a("  else if t < 3 / 2 then 5 / 6")
a("  else if t < 5 / 3 then 10 / 13")
a("  else if t < 15 / 8 then 5 / 7")
a("  else if t ≤ 104 / 15 then 9 / 13")
a("  else if t ≤ 39 / 5 then 5 / 7")
a("  else if t ≤ 26 / 3 then 10 / 13")
a("  else if t ≤ 65 / 6 then 5 / 6")
a("  else 1")
a("")
a("lemma c13ContinuousSupersolutionHeight_pos (t : ℝ) :")
a("    0 < c13ContinuousSupersolutionHeight t := by")
a("  unfold c13ContinuousSupersolutionHeight")
a("  split_ifs <;> norm_num")
a("")
a("def c13ContinuousPrimeTranslationRowFactor (t q : ℝ) : ℝ :=")
a("  (if t * q ≤ 13 then c13ContinuousSupersolutionHeight (t * q) else 0) +")
a("  (if q ≤ t then c13ContinuousSupersolutionHeight (t / q) else 0)")
a("")
a("lemma c13ContinuousPrimeTranslationRowFactor_nonneg (t q : ℝ) :")
a("    0 ≤ c13ContinuousPrimeTranslationRowFactor t q := by")
a("  unfold c13ContinuousPrimeTranslationRowFactor")
a("  apply add_nonneg")
a("  · split_ifs")
a("    · exact (c13ContinuousSupersolutionHeight_pos (t * q)).le")
a("    · norm_num")
a("  · split_ifs")
a("    · exact (c13ContinuousSupersolutionHeight_pos (t / q)).le")
a("    · norm_num")
a("")
a("def c13ContinuousUpperPrimeTranslationRow (t : ℝ) : ℝ :=")
for i,(q,w) in enumerate(EVENTS):
    suffix = " +" if i < len(EVENTS)-1 else ""
    a(f"  ({fmt(w)}) * c13ContinuousPrimeTranslationRowFactor t {q}{suffix}")
a("")
a("def c13ContinuousActualPrimeTranslationRow (t : ℝ) : ℝ :=")
true_weights = {
    2:"Real.log 2 / Real.sqrt 2", 3:"Real.log 3 / Real.sqrt 3",
    4:"Real.log 2 / Real.sqrt 4", 5:"Real.log 5 / Real.sqrt 5",
    7:"Real.log 7 / Real.sqrt 7", 8:"Real.log 2 / Real.sqrt 8",
    9:"Real.log 3 / Real.sqrt 9", 11:"Real.log 11 / Real.sqrt 11",
}
for i,(q,_w) in enumerate(EVENTS):
    suffix = " +" if i < len(EVENTS)-1 else ""
    a(f"  ({true_weights[q]}) * c13ContinuousPrimeTranslationRowFactor t {q}{suffix}")
a("")
a("theorem c13ContinuousActualPrimeTranslationRow_le_upper (t : ℝ) :")
a("    c13ContinuousActualPrimeTranslationRow t ≤")
a("      c13ContinuousUpperPrimeTranslationRow t := by")
a("  unfold c13ContinuousActualPrimeTranslationRow c13ContinuousUpperPrimeTranslationRow")
for q,name in [(2,"two"),(3,"three"),(4,"four"),(5,"five"),(7,"seven"),(8,"eight"),(9,"nine"),(11,"eleven")]:
    a(f"  have h{q} := mul_le_mul_of_nonneg_right weight_{name}_lt.le")
    a(f"    (c13ContinuousPrimeTranslationRowFactor_nonneg t {q})")
a("  linarith")
a("")
a("def c13ContinuousSupersolutionBreakpoints : List ℝ := [")
for i,x in enumerate(CUTS):
    comma = "," if i < len(CUTS)-1 else ""
    a(f"  {fmt(x,True)}{comma}")
a("]")
a("")
a("set_option maxRecDepth 100000 in")
a("set_option maxHeartbeats 0 in")
a("theorem c13ContinuousSupersolution_endpoint_rows_le :")
a("    ∀ t ∈ c13ContinuousSupersolutionBreakpoints,")
a("      c13ContinuousUpperPrimeTranslationRow t ≤")
a("        (33223 / 10000 : ℝ) * c13ContinuousSupersolutionHeight t := by")
a("  norm_num [c13ContinuousSupersolutionBreakpoints,")
a("    c13ContinuousUpperPrimeTranslationRow,")
a("    c13ContinuousPrimeTranslationRowFactor,")
a("    c13ContinuousSupersolutionHeight]")
a("")

for name,val,(lo,hi) in zip(REGION_NAMES,REGION_HEIGHT,REGION_BOUNDS):
    args=[]
    if lo is not None: args.append(f"(hL : {fmt(lo,True)} < x)")
    if hi is not None: args.append(f"(hR : x < {fmt(hi,True)})")
    a(f"private lemma c13ContinuousSupersolutionHeight_eq_{name} {{x : ℝ}} {' '.join(args)} :")
    a(f"    c13ContinuousSupersolutionHeight x = {fmt(val,True)} := by")
    a("  unfold c13ContinuousSupersolutionHeight")
    a("  split_ifs <;> linarith")
    a("")

def helper_call(reg):
    lo,hi=REGION_BOUNDS[reg]
    args=[]
    if lo is not None: args.append("(by linarith)")
    if hi is not None: args.append("(by linarith)")
    return f"c13ContinuousSupersolutionHeight_eq_{REGION_NAMES[reg]} {' '.join(args)}"

for idx,(left,right) in enumerate(zip(CUTS,CUTS[1:])):
    sample=(left+right)/2
    a("set_option maxRecDepth 100000 in")
    a("set_option maxHeartbeats 0 in")
    a(f"private theorem c13ContinuousSupersolution_openCell_{idx:02d} (t : ℝ)")
    a(f"    (hL : {fmt(left,True)} < t) (hR : t < {fmt(right,True)}) :")
    a("    c13ContinuousUpperPrimeTranslationRow t ≤")
    a("      (33223 / 10000 : ℝ) * c13ContinuousSupersolutionHeight t := by")
    treg=region(sample)
    a(f"  have ht : c13ContinuousSupersolutionHeight t = {fmt(REGION_HEIGHT[treg],True)} :=")
    a(f"    {helper_call(treg)}")
    factor_names=[]
    for q,_w in EVENTS:
        qf=F(q); plus=sample*qf<C; minus=qf<sample
        pieces=[]; refs=[]
        if plus:
            reg=region(sample*qf); nm=f"h{q}p"
            a(f"  have {nm} : c13ContinuousSupersolutionHeight (t * {q}) = {fmt(REGION_HEIGHT[reg],True)} :=")
            a(f"    {helper_call(reg)}")
            pieces.append(height(sample*qf)); refs.append(nm)
        if minus:
            reg=region(sample/qf); nm=f"h{q}m"
            a(f"  have {nm} : c13ContinuousSupersolutionHeight (t / {q}) = {fmt(REGION_HEIGHT[reg],True)} :=")
            a(f"    {helper_call(reg)}")
            pieces.append(height(sample/qf)); refs.append(nm)
        factor=sum(pieces,F(0)); nm=f"h{q}"; factor_names.append(nm)
        hp=f"show t * {q} ≤ 13 by linarith" if plus else f"show ¬ t * {q} ≤ 13 by linarith"
        hm=f"show {q} ≤ t by linarith" if minus else f"show ¬ {q} ≤ t by linarith"
        a(f"  have {nm} : c13ContinuousPrimeTranslationRowFactor t {q} = {fmt(factor,True)} := by")
        a(f"    norm_num [c13ContinuousPrimeTranslationRowFactor, {', '.join([hp,hm]+refs)}]")
    a("  rw [ht]")
    a("  simp only [c13ContinuousUpperPrimeTranslationRow, " + ", ".join(factor_names) + "]")
    a("  norm_num")
    a("")

a("private lemma c13ContinuousSupersolution_breakpoint_ne")
a("    {t b : ℝ} (ht : t ∉ c13ContinuousSupersolutionBreakpoints)")
a("    (hb : b ∈ c13ContinuousSupersolutionBreakpoints) : b ≠ t := by")
a("  intro h")
a("  apply ht")
a("  simpa only [h] using hb")
a("")
a("set_option maxRecDepth 100000 in")
a("set_option maxHeartbeats 0 in")
a("theorem c13ContinuousSupersolution_all_upper_rows_le (t : ℝ)")
a("    (htLower : (1 : ℝ) ≤ t) (htUpper : t ≤ 13) :")
a("    c13ContinuousUpperPrimeTranslationRow t ≤")
a("      (33223 / 10000 : ℝ) * c13ContinuousSupersolutionHeight t := by")
a("  by_cases htMem : t ∈ c13ContinuousSupersolutionBreakpoints")
a("  · exact c13ContinuousSupersolution_endpoint_rows_le t htMem")
a("  · have hPrev00 : (1 : ℝ) < t :=")
a("      lt_of_le_of_ne htLower")
a("        (c13ContinuousSupersolution_breakpoint_ne htMem")
a("          (by norm_num [c13ContinuousSupersolutionBreakpoints]))")
indent="    "
for idx in range(60):
    bp=CUTS[idx+1]
    a(indent+f"by_cases hNext{idx:02d} : t < {fmt(bp,True)}")
    a(indent+f"· exact c13ContinuousSupersolution_openCell_{idx:02d} t hPrev{idx:02d} hNext{idx:02d}")
    a(indent+f"· have hPrev{idx+1:02d} : {fmt(bp,True)} < t :=")
    a(indent+f"    lt_of_le_of_ne (le_of_not_gt hNext{idx:02d})")
    a(indent+"      (c13ContinuousSupersolution_breakpoint_ne htMem")
    a(indent+"        (by norm_num [c13ContinuousSupersolutionBreakpoints]))")
    indent += "  "
a(indent+"have hLast : t < (13 : ℝ) :=")
a(indent+"  lt_of_le_of_ne htUpper")
a(indent+"    (Ne.symm (c13ContinuousSupersolution_breakpoint_ne htMem")
a(indent+"      (by norm_num [c13ContinuousSupersolutionBreakpoints])))")
a(indent+"exact c13ContinuousSupersolution_openCell_60 t hPrev60 hLast")
a("")
a("theorem c13ContinuousActualPrimeTranslationRow_lt_tenThird (t : ℝ)")
a("    (htLower : (1 : ℝ) ≤ t) (htUpper : t ≤ 13) :")
a("    c13ContinuousActualPrimeTranslationRow t <")
a("      (10 / 3 : ℝ) * c13ContinuousSupersolutionHeight t := by")
a("  calc")
a("    c13ContinuousActualPrimeTranslationRow t")
a("        ≤ c13ContinuousUpperPrimeTranslationRow t :=")
a("      c13ContinuousActualPrimeTranslationRow_le_upper t")
a("    _ ≤ (33223 / 10000 : ℝ) * c13ContinuousSupersolutionHeight t :=")
a("      c13ContinuousSupersolution_all_upper_rows_le t htLower htUpper")
a("    _ < (10 / 3 : ℝ) * c13ContinuousSupersolutionHeight t := by")
a("      apply mul_lt_mul_of_pos_right _ (c13ContinuousSupersolutionHeight_pos t)")
a("      norm_num")
a("")
a("end RiemannCvs.PrimeTranslationSupersolution")
a("")

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(
            "research/riemann-cvs-lean/RiemannCvs/"
            "PrimeTranslationContinuousSupersolution.lean"
        ),
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    payload = "\n".join(lines).encode("utf-8")
    if args.check:
        if not args.output.is_file() or args.output.read_bytes() != payload:
            raise SystemExit(f"generated Lean module is stale: {args.output}")
        status = "PASS"
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_bytes(payload)
        status = "WRITTEN"
    print(
        json.dumps(
            {
                "status": status,
                "output": str(args.output.resolve()),
                "breakpoints": len(CUTS),
                "open_cells": len(CUTS) - 1,
                "lines": len(lines),
                "bytes": len(payload),
                "sha256": hashlib.sha256(payload).hexdigest().upper(),
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
