import Mathlib

/-!
# Scalar ADI telescope for Loewner displacement blocks

This file isolates the algebra behind the explicit low-rank factors used by
the adjacent-shell certificate.  A shift is stored as `(root, pole)`.
-/

namespace RiemannCvs

variable {𝕜 : Type*} [Field 𝕜]

/-- One quotient factor in `r(a) / r(b)`, written without nested division. -/
def adiStepRatio (shift : 𝕜 × 𝕜) (a b : 𝕜) : 𝕜 :=
  ((a - shift.1) * (b - shift.2)) /
    ((a - shift.2) * (b - shift.1))

/-- The product ratio `r(a) / r(b)` in cancellation-friendly form. -/
def adiRationalRatio : List (𝕜 × 𝕜) → 𝕜 → 𝕜 → 𝕜
  | [], _a, _b => 1
  | shift :: shifts, a, b =>
      adiStepRatio shift a b * adiRationalRatio shifts a b

/-- The scalar compressed entry generated by the ordered ADI shifts. -/
def adiCompressedEntry : List (𝕜 × 𝕜) → 𝕜 → 𝕜 → 𝕜 → 𝕜
  | [], _a, _b, _g => 0
  | (root, pole) :: shifts, a, b, g =>
      g * (pole - root) / ((a - pole) * (b - root)) +
        adiStepRatio (root, pole) a b *
          adiCompressedEntry shifts a b g

/-- The ordinary rational product `prod (x-root)/(x-pole)`. -/
def adiRationalProduct : List (𝕜 × 𝕜) → 𝕜 → 𝕜
  | [], _x => 1
  | (root, pole) :: shifts, x =>
      ((x - root) / (x - pole)) * adiRationalProduct shifts x

/-- Exact product of the left/right factors emitted by the certificate.
`leftPrefix` and `rightInversePrefix` are the running products in the script. -/
def adiFactorDotAux :
    𝕜 → 𝕜 → List (𝕜 × 𝕜) → 𝕜 → 𝕜 → 𝕜 → 𝕜 → 𝕜
  | _leftPrefix, _rightInversePrefix, [], _a, _b, _u, _v => 0
  | leftPrefix, rightInversePrefix, (root, pole) :: shifts, a, b, u, v =>
      (leftPrefix * (pole - root) / (a - pole) * u) *
          (rightInversePrefix / (b - root) * v) +
        adiFactorDotAux
          (leftPrefix * ((a - root) / (a - pole)))
          (rightInversePrefix * ((b - pole) / (b - root)))
          shifts a b u v

/-- Exact dot product of all rank-one ADI factor columns. -/
def adiFactorDot (shifts : List (𝕜 × 𝕜)) (a b u v : 𝕜) : 𝕜 :=
  adiFactorDotAux 1 1 shifts a b u v

lemma one_sub_adiStepRatio_div
    (a b root pole : 𝕜)
    (hab : a ≠ b) (haPole : a ≠ pole) (hbRoot : b ≠ root) :
    (1 - adiStepRatio (root, pole) a b) / (a - b) =
      (pole - root) / ((a - pole) * (b - root)) := by
  unfold adiStepRatio
  field_simp
  ring

lemma adiRationalProduct_ne_zero
    (shifts : List (𝕜 × 𝕜)) (x : 𝕜)
    (hRoot : ∀ shift ∈ shifts, x ≠ shift.1)
    (hPole : ∀ shift ∈ shifts, x ≠ shift.2) :
    adiRationalProduct shifts x ≠ 0 := by
  induction shifts with
  | nil => simp [adiRationalProduct]
  | cons shift shifts ih =>
      rcases shift with ⟨root, pole⟩
      have hRootHead : x ≠ root := hRoot (root, pole) (by simp)
      have hPoleHead : x ≠ pole := hPole (root, pole) (by simp)
      have hRootTail : ∀ shift ∈ shifts, x ≠ shift.1 := by
        intro shift hShift
        exact hRoot shift (by simp [hShift])
      have hPoleTail : ∀ shift ∈ shifts, x ≠ shift.2 := by
        intro shift hShift
        exact hPole shift (by simp [hShift])
      simp only [adiRationalProduct]
      exact mul_ne_zero
        (div_ne_zero (sub_ne_zero.mpr hRootHead) (sub_ne_zero.mpr hPoleHead))
        (ih hRootTail hPoleTail)

lemma adiRationalRatio_eq_product_div
    (shifts : List (𝕜 × 𝕜)) (a b : 𝕜)
    (haPole : ∀ shift ∈ shifts, a ≠ shift.2)
    (hbRoot : ∀ shift ∈ shifts, b ≠ shift.1)
    (hbPole : ∀ shift ∈ shifts, b ≠ shift.2) :
    adiRationalRatio shifts a b =
      adiRationalProduct shifts a / adiRationalProduct shifts b := by
  induction shifts with
  | nil => simp [adiRationalRatio, adiRationalProduct]
  | cons shift shifts ih =>
      rcases shift with ⟨root, pole⟩
      have haPoleHead : a ≠ pole := haPole (root, pole) (by simp)
      have hbRootHead : b ≠ root := hbRoot (root, pole) (by simp)
      have hbPoleHead : b ≠ pole := hbPole (root, pole) (by simp)
      have haPoleTail : ∀ shift ∈ shifts, a ≠ shift.2 := by
        intro shift hShift
        exact haPole shift (by simp [hShift])
      have hbRootTail : ∀ shift ∈ shifts, b ≠ shift.1 := by
        intro shift hShift
        exact hbRoot shift (by simp [hShift])
      have hbPoleTail : ∀ shift ∈ shifts, b ≠ shift.2 := by
        intro shift hShift
        exact hbPole shift (by simp [hShift])
      rw [adiRationalRatio, adiRationalProduct, adiRationalProduct]
      rw [ih haPoleTail hbRootTail hbPoleTail]
      have hTail := adiRationalProduct_ne_zero shifts b
        hbRootTail hbPoleTail
      unfold adiStepRatio
      field_simp

/-- The scalar telescope behind the ADI compression. -/
theorem loewner_adi_scalar_telescope
    (shifts : List (𝕜 × 𝕜)) (a b g : 𝕜)
    (hab : a ≠ b)
    (haPole : ∀ shift ∈ shifts, a ≠ shift.2)
    (hbRoot : ∀ shift ∈ shifts, b ≠ shift.1) :
    g / (a - b) * (1 - adiRationalRatio shifts a b) =
      adiCompressedEntry shifts a b g := by
  induction shifts with
  | nil => simp [adiRationalRatio, adiCompressedEntry]
  | cons shift shifts ih =>
      rcases shift with ⟨root, pole⟩
      have haPoleHead : a ≠ pole := haPole (root, pole) (by simp)
      have hbRootHead : b ≠ root := hbRoot (root, pole) (by simp)
      have haPoleTail : ∀ shift ∈ shifts, a ≠ shift.2 := by
        intro shift hShift
        exact haPole shift (by simp [hShift])
      have hbRootTail : ∀ shift ∈ shifts, b ≠ shift.1 := by
        intro shift hShift
        exact hbRoot shift (by simp [hShift])
      rw [adiRationalRatio, adiCompressedEntry]
      have hStep := one_sub_adiStepRatio_div a b root pole
        hab haPoleHead hbRootHead
      calc
        g / (a - b) *
            (1 - adiStepRatio (root, pole) a b *
              adiRationalRatio shifts a b) =
            g / (a - b) * (1 - adiStepRatio (root, pole) a b) +
              adiStepRatio (root, pole) a b *
                (g / (a - b) *
                  (1 - adiRationalRatio shifts a b)) := by ring
        _ = g * ((1 - adiStepRatio (root, pole) a b) / (a - b)) +
              adiStepRatio (root, pole) a b *
                adiCompressedEntry shifts a b g := by
              rw [ih haPoleTail hbRootTail]
              ring
        _ = g * (pole - root) / ((a - pole) * (b - root)) +
              adiStepRatio (root, pole) a b *
                adiCompressedEntry shifts a b g := by
              rw [hStep]
              simp only [div_eq_mul_inv]
              ring

lemma adiFactorDotAux_eq_prefix_mul_compressed
    (shifts : List (𝕜 × 𝕜))
    (leftPrefix rightInversePrefix a b u v : 𝕜) :
    adiFactorDotAux leftPrefix rightInversePrefix shifts a b u v =
      leftPrefix * rightInversePrefix *
        adiCompressedEntry shifts a b (u * v) := by
  induction shifts generalizing leftPrefix rightInversePrefix with
  | nil => simp [adiFactorDotAux, adiCompressedEntry]
  | cons shift shifts ih =>
      rcases shift with ⟨root, pole⟩
      rw [adiFactorDotAux, adiCompressedEntry, ih]
      unfold adiStepRatio
      simp only [div_eq_mul_inv, mul_inv_rev]
      ring

lemma adiFactorDot_eq_compressed
    (shifts : List (𝕜 × 𝕜)) (a b u v : 𝕜) :
    adiFactorDot shifts a b u v =
      adiCompressedEntry shifts a b (u * v) := by
  unfold adiFactorDot
  rw [adiFactorDotAux_eq_prefix_mul_compressed]
  ring

lemma adiCompressedEntry_add
    (shifts : List (𝕜 × 𝕜)) (a b g h : 𝕜) :
    adiCompressedEntry shifts a b (g + h) =
      adiCompressedEntry shifts a b g + adiCompressedEntry shifts a b h := by
  induction shifts with
  | nil => simp [adiCompressedEntry]
  | cons shift shifts ih =>
      rcases shift with ⟨root, pole⟩
      rw [adiCompressedEntry, adiCompressedEntry, adiCompressedEntry, ih]
      ring

/-- Rank-two Loewner displacement gives exactly two factor columns per shift. -/
theorem loewner_adi_rankTwo_factorization
    (shifts : List (𝕜 × 𝕜))
    (a b x u0 u1 v0 v1 : 𝕜)
    (hab : a ≠ b)
    (haPole : ∀ shift ∈ shifts, a ≠ shift.2)
    (hbRoot : ∀ shift ∈ shifts, b ≠ shift.1)
    (hDisplacement : (a - b) * x = u0 * v0 + u1 * v1) :
    x * (1 - adiRationalRatio shifts a b) =
      adiFactorDot shifts a b u0 v0 +
        adiFactorDot shifts a b u1 v1 := by
  have hab0 : a - b ≠ 0 := sub_ne_zero.mpr hab
  have hx : x = (u0 * v0 + u1 * v1) / (a - b) := by
    apply (eq_div_iff hab0).2
    simpa [mul_comm] using hDisplacement
  rw [hx, loewner_adi_scalar_telescope shifts a b (u0 * v0 + u1 * v1)
    hab haPole hbRoot]
  rw [adiCompressedEntry_add, adiFactorDot_eq_compressed,
    adiFactorDot_eq_compressed]

/-- Certificate-facing form with the ordinary rational product quotient. -/
theorem loewner_adi_rankTwo_factorization_rationalProduct
    (shifts : List (𝕜 × 𝕜))
    (a b x u0 u1 v0 v1 : 𝕜)
    (hab : a ≠ b)
    (haPole : ∀ shift ∈ shifts, a ≠ shift.2)
    (hbRoot : ∀ shift ∈ shifts, b ≠ shift.1)
    (hbPole : ∀ shift ∈ shifts, b ≠ shift.2)
    (hDisplacement : (a - b) * x = u0 * v0 + u1 * v1) :
    x * (1 - adiRationalProduct shifts a / adiRationalProduct shifts b) =
      adiFactorDot shifts a b u0 v0 +
        adiFactorDot shifts a b u1 v1 := by
  rw [← adiRationalRatio_eq_product_div shifts a b haPole hbRoot hbPole]
  exact loewner_adi_rankTwo_factorization shifts a b x u0 u1 v0 v1
    hab haPole hbRoot hDisplacement

/-- A scaled off-diagonal Loewner entry.  Keeping independent left and right
scales matches the balanced `1/sqrt K` normalization used by the finite Gram
certificate. -/
def scaledLoewnerEntry
    (leftScale rightScale : 𝕜) (symbol : 𝕜 → 𝕜) (a b : 𝕜) : 𝕜 :=
  leftScale * rightScale * (symbol b - symbol a) / (a - b)

/-- The scaled Loewner entry has the exact rank-two displacement generator
used by the explicit factor construction. -/
lemma scaledLoewnerEntry_displacement
    (leftScale rightScale : 𝕜) (symbol : 𝕜 → 𝕜) (a b : 𝕜)
    (hab : a ≠ b) :
    (a - b) * scaledLoewnerEntry leftScale rightScale symbol a b =
      (-symbol a * leftScale) * rightScale +
        leftScale * (symbol b * rightScale) := by
  have hab0 : a - b ≠ 0 := sub_ne_zero.mpr hab
  unfold scaledLoewnerEntry
  field_simp
  ring

/-- Certificate-facing ADI factorization for a scaled Loewner entry.  The two
factor columns at each shift are exactly

`(-symbol a * leftScale, leftScale)` on the left and
`(rightScale, symbol b * rightScale)` on the right.

Taking `symbol = g / pi`, `leftScale = rightScale = 1 / sqrt K`,
`a = p/K`, and `b = q/K` gives the same-sign certificate block.  Taking
`b = -q/K` gives the reflected block without changing the theorem. -/
theorem scaledLoewnerEntry_adi_factorization_rationalProduct
    (shifts : List (𝕜 × 𝕜))
    (leftScale rightScale : 𝕜) (symbol : 𝕜 → 𝕜) (a b : 𝕜)
    (hab : a ≠ b)
    (haPole : ∀ shift ∈ shifts, a ≠ shift.2)
    (hbRoot : ∀ shift ∈ shifts, b ≠ shift.1)
    (hbPole : ∀ shift ∈ shifts, b ≠ shift.2) :
    scaledLoewnerEntry leftScale rightScale symbol a b *
        (1 - adiRationalProduct shifts a / adiRationalProduct shifts b) =
      adiFactorDot shifts a b (-symbol a * leftScale) rightScale +
        adiFactorDot shifts a b leftScale (symbol b * rightScale) := by
  exact loewner_adi_rankTwo_factorization_rationalProduct
    shifts a b (scaledLoewnerEntry leftScale rightScale symbol a b)
    (-symbol a * leftScale) leftScale rightScale (symbol b * rightScale)
    hab haPole hbRoot hbPole
    (scaledLoewnerEntry_displacement leftScale rightScale symbol a b hab)

end RiemannCvs
